### ISSUE TITLE
Not all Restaurants are found

### ISSUE THREAD

**Issue by w1ll1am23** [tuchfarber/Veto-It#5] opened 2017-03-23 16:35 UTC
Using address in Blue Ash Ohio for example 10375 Kenwood Road Cincinnati, OH 45242 

Doesn't find the City Barbeque.

![image](https://cloud.githubusercontent.com/assets/6432770/24258748/17b65894-0fc5-11e7-8700-b4b2e68897bc.png)

**Comment by tuchfarber** [comment] 2017-03-27 21:38
Possibly switching to Radar search which allows up to 200 results: https://developers.google.com/maps/documentation/javascript/examples/place-radar-search

**Comment by tuchfarber** [comment] 2017-03-27 21:41
Duplicate of [#3](https://github.com/tuchfarber/Veto-It/issues/3)

**Closed as completed by tuchfarber** 2017-03-27 21:41 UTC
